version: '3.8'

services:
  androboss:
    build: .
    container_name: androboss
    volumes:
      - .:/app
      - samsebweb_androboss_media:/app/media
    env_file:
      - .env
    networks:
      - samsebweb_app-network
    restart: unless-stopped

volumes:
  samsebweb_androboss_media:
    external: true

networks:
  samsebweb_app-network:
    external: true
