# Generated by Django 4.2.30 on 2026-04-16 12:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ism')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefon')),
                ('discount', models.IntegerField(default=0, verbose_name='Chegirma (%)')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('called', "Qo'ng'iroq qilindi"), ('confirmed', 'Tasdiqlandi'), ('cancelled', 'Bekor qilindi')], default='new', max_length=20, verbose_name='Holat')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitorStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, unique=True, verbose_name='Sana')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Tashriflar')),
            ],
            options={
                'verbose_name': 'Tashrif statistikasi',
                'verbose_name_plural': 'Tashrif statistikasi',
                'ordering': ['-date'],
            },
        ),
    ]
