# Generated by Django 4.2.30 on 2026-04-17 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_telegramadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Familiya')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='reviews/avatars/', verbose_name='Profil rasmi')),
                ('rating', models.IntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], default=5, verbose_name='Reyting')),
                ('text', models.TextField(verbose_name='Sharh matni')),
                ('date', models.DateField(verbose_name='Sana')),
                ('is_active', models.BooleanField(default=True, verbose_name="Ko'rsatish")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Sharh',
                'verbose_name_plural': 'Sharhlar',
                'ordering': ['order', '-date'],
            },
        ),
        migrations.CreateModel(
            name='ReviewMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Rasm'), ('video', 'Video'), ('audio', 'Ovoz xabari')], max_length=10, verbose_name='Tur')),
                ('file', models.FileField(upload_to='reviews/media/', verbose_name='Fayl')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='shop.review', verbose_name='Sharh')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media fayllar',
                'ordering': ['order'],
            },
        ),
    ]
